export const demoExams = [
  {
    id: "demo-enem",
    slug: "enem",
    name: "Exame Nacional do Ensino Médio",
    acronym: "ENEM",
    institution:
      "Instituto Nacional de Estudos e Pesquisas Educacionais Anísio Teixeira",
    board: "INEP",
    region: "Brasil",
    officialUrl:
      "https://www.gov.br/inep/pt-br/areas-de-atuacao/avaliacao-e-exames-educacionais/enem",
    sourceUrl:
      "https://www.gov.br/inep/pt-br/areas-de-atuacao/avaliacao-e-exames-educacionais/enem",
    summary:
      "Avaliação nacional usada no acesso ao ensino superior, organizada em quatro áreas e redação.",
    rightsStatus: "official_link" as const,
    version: 1,
    verifiedAt: new Date("2026-08-01T00:00:00.000Z"),
  },
  {
    id: "demo-fuvest",
    slug: "fuvest",
    name: "Vestibular da Universidade de São Paulo",
    acronym: "FUVEST",
    institution: "Universidade de São Paulo",
    board: "FUVEST",
    region: "São Paulo",
    officialUrl: "https://www.fuvest.br/",
    sourceUrl: "https://www.fuvest.br/",
    summary:
      "Processo seletivo da USP com etapas e regras versionadas por edição.",
    rightsStatus: "official_link" as const,
    version: 1,
    verifiedAt: new Date("2026-08-01T00:00:00.000Z"),
  },
  {
    id: "demo-unicamp",
    slug: "unicamp",
    name: "Vestibular da Universidade Estadual de Campinas",
    acronym: "UNICAMP",
    institution: "Universidade Estadual de Campinas",
    board: "COMVEST",
    region: "São Paulo",
    officialUrl: "https://www.comvest.unicamp.br/",
    sourceUrl: "https://www.comvest.unicamp.br/vestibulares-anteriores/",
    summary: "Seleção da Unicamp com primeira e segunda fases e redação.",
    rightsStatus: "official_link" as const,
    version: 1,
    verifiedAt: new Date("2026-08-01T00:00:00.000Z"),
  },
  {
    id: "demo-uerj",
    slug: "uerj",
    name: "Vestibular Estadual do Rio de Janeiro",
    acronym: "UERJ",
    institution: "Universidade do Estado do Rio de Janeiro",
    board: "CEPUERJ",
    region: "Rio de Janeiro",
    officialUrl: "https://www.cepuerj.uerj.br/",
    sourceUrl: "https://www.cepuerj.uerj.br/",
    summary:
      "Processo seletivo da UERJ com exame de qualificação e discursiva-objetiva.",
    rightsStatus: "official_link" as const,
    version: 1,
    verifiedAt: new Date("2026-08-01T00:00:00.000Z"),
  },
  {
    id: "demo-unesp",
    slug: "unesp",
    name: "Vestibular da Universidade Estadual Paulista",
    acronym: "UNESP",
    institution: "Universidade Estadual Paulista",
    board: "VUNESP",
    region: "São Paulo",
    officialUrl: "https://www.vunesp.com.br/",
    sourceUrl: "https://www.vunesp.com.br/",
    summary:
      "Processo seletivo da Unesp aplicado pela Vunesp, sem lista de leituras obrigatórias.",
    rightsStatus: "official_link" as const,
    version: 1,
    verifiedAt: new Date("2026-08-01T00:00:00.000Z"),
  },
  {
    id: "demo-ufpr",
    slug: "ufpr",
    name: "Vestibular da Universidade Federal do Paraná",
    acronym: "UFPR",
    institution: "Universidade Federal do Paraná",
    board: "NC-UFPR",
    region: "Paraná",
    officialUrl: "https://www.nc.ufpr.br/",
    sourceUrl: "https://www.nc.ufpr.br/",
    summary: "Processo seletivo da UFPR conduzido pelo Núcleo de Concursos.",
    rightsStatus: "official_link" as const,
    version: 1,
    verifiedAt: new Date("2026-08-01T00:00:00.000Z"),
  },
  {
    id: "demo-ufrgs",
    slug: "ufrgs",
    name: "Vestibular da Universidade Federal do Rio Grande do Sul",
    acronym: "UFRGS",
    institution: "Universidade Federal do Rio Grande do Sul",
    board: "COPERSE",
    region: "Rio Grande do Sul",
    officialUrl: "https://www.ufrgs.br/coperse/",
    sourceUrl: "https://www.ufrgs.br/coperse/",
    summary: "Processo seletivo da UFRGS conduzido pela COPERSE.",
    rightsStatus: "official_link" as const,
    version: 1,
    verifiedAt: new Date("2026-08-01T00:00:00.000Z"),
  },
];

export const demoSubjects = [
  {
    id: "demo-matematica",
    slug: "matematica",
    name: "Matemática",
    area: "mathematics" as const,
    summary:
      "Aritmética, álgebra, funções, geometria, estatística e probabilidade.",
  },
  {
    id: "demo-portugues",
    slug: "lingua-portuguesa",
    name: "Língua Portuguesa",
    area: "languages" as const,
    summary: "Interpretação, gramática, literatura e produção de texto.",
  },
  {
    id: "demo-biologia",
    slug: "biologia",
    name: "Biologia",
    area: "natural_sciences" as const,
    summary: "Citologia, genética, evolução, ecologia e fisiologia.",
  },
  {
    id: "demo-historia",
    slug: "historia",
    name: "História",
    area: "human_sciences" as const,
    summary:
      "Processos históricos do Brasil e do mundo em perspectiva crítica.",
  },
  {
    id: "demo-quimica",
    slug: "quimica",
    name: "Química",
    area: "natural_sciences" as const,
    summary:
      "Química orgânica, inorgânica, estequiometria, termoquímica e eletroquímica.",
  },
  {
    id: "demo-fisica",
    slug: "fisica",
    name: "Física",
    area: "natural_sciences" as const,
    summary: "Mecânica, termologia, eletricidade, óptica e ondulatória.",
  },
  {
    id: "demo-literatura",
    slug: "literatura",
    name: "Literatura",
    area: "languages" as const,
    summary:
      "Escolas literárias, movimentos e análise de obras da literatura brasileira e portuguesa.",
  },
  {
    id: "demo-redacao",
    slug: "redacao",
    name: "Redação",
    area: "languages" as const,
    summary:
      "Estrutura dissertativo-argumentativa, repertório sociocultural e proposta de intervenção.",
  },
  {
    id: "demo-geografia",
    slug: "geografia",
    name: "Geografia",
    area: "human_sciences" as const,
    summary: "Geografia física, humana, geopolítica e geografia do Brasil.",
  },
  {
    id: "demo-filosofia",
    slug: "filosofia",
    name: "Filosofia",
    area: "human_sciences" as const,
    summary: "Filosofia antiga, moderna, contemporânea, ética e política.",
  },
  {
    id: "demo-sociologia",
    slug: "sociologia",
    name: "Sociologia",
    area: "human_sciences" as const,
    summary:
      "Clássicos da sociologia, cultura, estratificação e movimentos sociais.",
  },
  {
    id: "demo-ingles",
    slug: "ingles",
    name: "Inglês",
    area: "languages" as const,
    summary:
      "Interpretação de texto, gramática e estratégias de leitura em inglês.",
  },
  {
    id: "demo-espanhol",
    slug: "espanhol",
    name: "Espanhol",
    area: "languages" as const,
    summary: "Interpretação de texto, gramática e cultura hispano-americana.",
  },
  {
    id: "demo-artes",
    slug: "artes",
    name: "Artes",
    area: "languages" as const,
    summary: "História da arte, arte brasileira e movimentos artísticos.",
  },
  {
    id: "demo-educacao-fisica",
    slug: "educacao-fisica",
    name: "Educação Física",
    area: "languages" as const,
    summary: "Cultura corporal, esporte, saúde e qualidade de vida.",
  },
];
