export type SubjectSlug =
  | "matematica"
  | "lingua-portuguesa"
  | "biologia"
  | "historia"
  | "quimica"
  | "fisica"
  | "literatura"
  | "redacao"
  | "geografia"
  | "filosofia"
  | "sociologia"
  | "ingles"
  | "espanhol"
  | "artes"
  | "educacao-fisica";

export type LessonVideo = {
  slug: string;
  name: string;
  /** "Frente" grouping this módulo belongs to (Área → Matéria → Frente → Módulo → Aula). */
  frenteSlug: string;
  frenteName: string;
  videoTitle: string;
  channel: string;
  videoUrl: string;
  estimatedMinutes: number;
  /** Short "o que você precisa saber antes" line — omit when there's none. */
  prerequisiteSummary?: string;
};

/**
 * Curated (not API-searched) YouTube videos per subject subtopic, embedded
 * directly on the lesson page. Picked from established Brazilian ENEM/
 * vestibular-prep channels; update by replacing videoUrl.
 */
export const lessonVideosBySubject: Record<SubjectSlug, LessonVideo[]> = {
  matematica: [
    {
      slug: "funcoes",
      name: "Funções",
      frenteSlug: "frente-funcoes",
      frenteName: "Funções",
      videoTitle: "Funções: Noções Básicas (Aula 1 de 15)",
      channel: "Professor Ferretto | ENEM e Vestibulares",
      videoUrl: "https://www.youtube.com/watch?v=SPZqQ5qn3P0",
      estimatedMinutes: 20,
      prerequisiteSummary: "Operações básicas e plano cartesiano",
    },
    {
      slug: "geometria-plana",
      name: "Geometria Plana",
      frenteSlug: "frente-geometria-plana",
      frenteName: "Geometria plana",
      videoTitle:
        "Geometria Plana | AULA do ZERO - Matemática | Me Salva! ENEM 2021",
      channel: "Me Salva! ENEM",
      videoUrl: "https://www.youtube.com/watch?v=mxtBAXqFCcM",
      estimatedMinutes: 35,
    },
    {
      slug: "estatistica-e-probabilidade",
      name: "Estatística e Probabilidade",
      frenteSlug: "frente-probabilidade",
      frenteName: "Análise combinatória e probabilidade",
      videoTitle: "Estatística e Probabilidade - Aula 01 - Aleatoriedade",
      channel: "UNIVESP",
      videoUrl: "https://www.youtube.com/watch?v=VRiFnz7Di20",
      estimatedMinutes: 15,
    },
    {
      slug: "porcentagem-e-juros",
      name: "Porcentagem e Juros",
      frenteSlug: "frente-matematica-financeira",
      frenteName: "Matemática financeira",
      videoTitle: "MATEMÁTICA FINANCEIRA (ENEM) - Aula 1: Porcentagem",
      channel: "Fique Tranquilo - Matemática com prof. Bruno",
      videoUrl: "https://www.youtube.com/watch?v=JKwkR-caXSw",
      estimatedMinutes: 20,
    },
    {
      slug: "trigonometria",
      name: "Trigonometria",
      frenteSlug: "frente-trigonometria",
      frenteName: "Trigonometria",
      videoTitle:
        "TRIGONOMETRIA NO TRIÂNGULO RETÂNGULO (ENEM) - Aula 1: Seno, cosseno e tangente",
      channel: "Fique Tranquilo - Matemática com prof. Bruno",
      videoUrl: "https://www.youtube.com/watch?v=xkMKPDqPEjE",
      estimatedMinutes: 20,
      prerequisiteSummary: "Semelhança de triângulos e Teorema de Pitágoras",
    },
  ],
  "lingua-portuguesa": [
    {
      slug: "interpretacao-de-texto",
      name: "Interpretação de Texto",
      frenteSlug: "frente-interpretacao-textual",
      frenteName: "Interpretação textual",
      videoTitle: "Compreensão e Interpretação de Texto – Revisão ENEM",
      channel: "Professor Noslen",
      videoUrl: "https://www.youtube.com/watch?v=XsN0e_xPyNI",
      estimatedMinutes: 25,
    },
    {
      slug: "figuras-de-linguagem",
      name: "Figuras de Linguagem",
      frenteSlug: "frente-estilistica",
      frenteName: "Estilística",
      videoTitle:
        "FIGURAS DE LINGUAGEM: Aula COMPLETA para Você NÃO Errar Mais!",
      channel: "Português sem Enrolação - Professora Lis",
      videoUrl: "https://www.youtube.com/watch?v=zTe7izGQ8-4",
      estimatedMinutes: 25,
    },
    {
      slug: "concordancia-verbal-e-nominal",
      name: "Concordância Verbal e Nominal",
      frenteSlug: "frente-sintaxe",
      frenteName: "Sintaxe",
      videoTitle: "CONCORDÂNCIA VERBAL E NOMINAL - AULA 01",
      channel: "Pablo Jamilk",
      videoUrl: "https://www.youtube.com/watch?v=RgChoEg6enk",
      estimatedMinutes: 30,
    },
    {
      slug: "modernismo-brasileiro",
      name: "Literatura: Modernismo Brasileiro",
      frenteSlug: "frente-escolas-literarias",
      frenteName: "Escolas literárias",
      videoTitle:
        "Literatura - Modernismo Brasileiro - Contexto Histórico | ENEM",
      channel: "Scribs - Redação ENEM",
      videoUrl: "https://www.youtube.com/watch?v=SD9tLEUnEME",
      estimatedMinutes: 20,
    },
    {
      slug: "redacao-nota-1000",
      name: "Redação Nota 1000",
      frenteSlug: "frente-redacao-enem",
      frenteName: "Redação do ENEM",
      videoTitle:
        "Como fazer sua primeira REDAÇÃO NOTA 1000 do ZERO (atualizado para 2026)",
      channel: "Profinho",
      videoUrl: "https://www.youtube.com/watch?v=Y86ZJPVhmZo",
      estimatedMinutes: 25,
      prerequisiteSummary: "Interpretação de texto e leitura de propostas",
    },
  ],
  biologia: [
    {
      slug: "citologia",
      name: "Citologia",
      frenteSlug: "frente-citologia",
      frenteName: "Citologia",
      videoTitle: "TUDO DE CITOLOGIA PARA O ENEM 2026 | DIDÁTICA MÁGICA",
      channel: "Pedro Assaad | ENEM 2026",
      videoUrl: "https://www.youtube.com/watch?v=I6XycvmojEo",
      estimatedMinutes: 30,
    },
    {
      slug: "genetica-e-hereditariedade",
      name: "Genética e Hereditariedade",
      frenteSlug: "frente-genetica",
      frenteName: "Genética",
      videoTitle: "INTRODUÇÃO À GENÉTICA | Resumo de Biologia para o Enem",
      channel: "Curso Enem Gratuito",
      videoUrl: "https://www.youtube.com/watch?v=JsLH-x_tSZ0",
      estimatedMinutes: 20,
      prerequisiteSummary: "Núcleo celular e DNA (citologia básica)",
    },
    {
      slug: "ecologia",
      name: "Ecologia",
      frenteSlug: "frente-ecologia",
      frenteName: "Ecologia",
      videoTitle: "Tudo sobre ECOLOGIA para o ENEM",
      channel: "Paulo Jubilut",
      videoUrl: "https://www.youtube.com/watch?v=Rr-zQYqRCzo",
      estimatedMinutes: 30,
    },
    {
      slug: "evolucao",
      name: "Evolução",
      frenteSlug: "frente-evolucao",
      frenteName: "Evolução",
      videoTitle: "Seleção Natural | Evolução no ENEM",
      channel: "Paulo Jubilut",
      videoUrl: "https://www.youtube.com/watch?v=Uodc0C4jFQs",
      estimatedMinutes: 20,
    },
    {
      slug: "fisiologia-humana",
      name: "Fisiologia Humana",
      frenteSlug: "frente-fisiologia-humana",
      frenteName: "Fisiologia humana",
      videoTitle: "SISTEMAS DO CORPO HUMANO - Resumo de Fisiologia",
      channel: "Biologia com Samuel Cunha",
      videoUrl: "https://www.youtube.com/watch?v=gz9BSAnNjKE",
      estimatedMinutes: 25,
    },
  ],
  historia: [
    {
      slug: "brasil-colonia",
      name: "Brasil Colônia",
      frenteSlug: "frente-historia-do-brasil",
      frenteName: "História do Brasil",
      videoTitle: "BRASIL COLÔNIA | Resumo de História do Brasil para o Enem",
      channel: "Curso Enem Gratuito",
      videoUrl: "https://www.youtube.com/watch?v=RX2eB7zf87g",
      estimatedMinutes: 20,
    },
    {
      slug: "era-vargas",
      name: "Era Vargas",
      frenteSlug: "frente-historia-do-brasil",
      frenteName: "História do Brasil",
      videoTitle:
        "ERA VARGAS (1930 – 1937) | Resumo de História do Brasil para o Enem",
      channel: "Curso Enem Gratuito",
      videoUrl: "https://www.youtube.com/watch?v=pqEDSyU6tsw",
      estimatedMinutes: 20,
      prerequisiteSummary: "Contexto da Primeira República (1889-1930)",
    },
    {
      slug: "guerra-fria",
      name: "Guerra Fria",
      frenteSlug: "frente-historia-geral",
      frenteName: "História Geral",
      videoTitle:
        "GUERRA FRIA ENTRE OS EUA E A URSS: conflitos e características | RESUMO DE HISTÓRIA ENEM",
      channel: "Curso Enem Gratuito",
      videoUrl: "https://www.youtube.com/watch?v=mjqfi1mOKLI",
      estimatedMinutes: 20,
    },
    {
      slug: "revolucao-industrial",
      name: "Revolução Industrial",
      frenteSlug: "frente-historia-geral",
      frenteName: "História Geral",
      videoTitle: "REVOLUÇÃO INDUSTRIAL | Resumo de História para o Enem",
      channel: "Curso Enem Gratuito",
      videoUrl: "https://www.youtube.com/watch?v=NFrNx3JOXSg",
      estimatedMinutes: 20,
    },
    {
      slug: "ditadura-militar",
      name: "Ditadura Militar no Brasil",
      frenteSlug: "frente-historia-do-brasil",
      frenteName: "História do Brasil",
      videoTitle:
        'DITADURA MILITAR: período é retratado em "Ainda Estou Aqui" | História para o Enem',
      channel: "Curso Enem Gratuito",
      videoUrl: "https://www.youtube.com/watch?v=D4TMrqvunls",
      estimatedMinutes: 20,
    },
  ],
  quimica: [
    {
      slug: "quimica-organica",
      name: "Química Orgânica",
      frenteSlug: "frente-quimica-organica",
      frenteName: "Química orgânica",
      videoTitle:
        "QUÍMICA ORGÂNICA: Tudo sobre Cadeias Carbônicas e Funções Orgânicas | ENEM e Vestibular",
      channel: "Toda Matéria",
      videoUrl: "https://www.youtube.com/watch?v=WQBpu-IbFKw",
      estimatedMinutes: 25,
    },
    {
      slug: "estequiometria",
      name: "Estequiometria",
      frenteSlug: "frente-fisico-quimica",
      frenteName: "Físico-Química",
      videoTitle: "ESTEQUIOMETRIA | Resumo de Química para o Enem",
      channel: "Curso Enem Gratuito",
      videoUrl: "https://www.youtube.com/watch?v=vodua1lGa68",
      estimatedMinutes: 20,
      prerequisiteSummary: "Mol e balanceamento de equações",
    },
    {
      slug: "quimica-inorganica-e-ligacoes",
      name: "Química Inorgânica e Ligações Químicas",
      frenteSlug: "frente-ligacoes-quimicas",
      frenteName: "Ligações químicas",
      videoTitle:
        "Ligações Químicas | AULA do ZERO - Química | Me Salva! ENEM 2021",
      channel: "Me Salva! ENEM",
      videoUrl: "https://www.youtube.com/watch?v=X5xOEgJtCHU",
      estimatedMinutes: 35,
    },
    {
      slug: "termoquimica",
      name: "Termoquímica",
      frenteSlug: "frente-fisico-quimica",
      frenteName: "Físico-Química",
      videoTitle: "Química para o ENEM - Termoquímica (variações de entalpia)",
      channel: "ProEnem - Enem 2026",
      videoUrl: "https://www.youtube.com/watch?v=2xEjPZ9p1B8",
      estimatedMinutes: 20,
    },
    {
      slug: "eletroquimica",
      name: "Eletroquímica",
      frenteSlug: "frente-fisico-quimica",
      frenteName: "Físico-Química",
      videoTitle: "AULA QUÍMICA - ELETROQUÍMICA: Pilhas",
      channel: "Stoodi",
      videoUrl: "https://www.youtube.com/watch?v=nTkxw0797eE",
      estimatedMinutes: 15,
      prerequisiteSummary: "Número de oxidação (Nox) e balanceamento redox",
    },
  ],
  fisica: [
    {
      slug: "mecanica",
      name: "Mecânica (Cinemática e Dinâmica)",
      frenteSlug: "frente-mecanica",
      frenteName: "Mecânica",
      videoTitle:
        "TUDO DE CINEMÁTICA PARA O ENEM!! - Física Básica Completa (MESTRES DO ENEM)",
      channel: "Umberto Mannarino - Mestres do ENEM",
      videoUrl: "https://www.youtube.com/watch?v=NCxNuTLIu9Y",
      estimatedMinutes: 30,
    },
    {
      slug: "eletricidade",
      name: "Eletricidade",
      frenteSlug: "frente-eletrodinamica",
      frenteName: "Eletrodinâmica",
      videoTitle:
        "MEGA REVISÃO COMPLETA de FÍSICA para o ENEM | ELETRICIDADE | Aula 03",
      channel: "Professor Boaro",
      videoUrl: "https://www.youtube.com/watch?v=6yIdTlAFhZY",
      estimatedMinutes: 30,
      prerequisiteSummary: "Grandezas físicas básicas e Leis de Newton",
    },
    {
      slug: "termologia",
      name: "Termologia",
      frenteSlug: "frente-termologia",
      frenteName: "Termologia",
      videoTitle:
        "CALORIMETRIA: aprenda os conceitos iniciais | Física para o Enem",
      channel: "Curso Enem Gratuito",
      videoUrl: "https://www.youtube.com/watch?v=E4B0RatuhI4",
      estimatedMinutes: 20,
    },
    {
      slug: "optica",
      name: "Óptica",
      frenteSlug: "frente-optica",
      frenteName: "Óptica",
      videoTitle: "ÓPTICA: aprenda os conceitos iniciais | Física para o Enem",
      channel: "Curso Enem Gratuito",
      videoUrl: "https://www.youtube.com/watch?v=B4LQMZluelI",
      estimatedMinutes: 20,
      prerequisiteSummary: "Propagação retilínea da luz",
    },
    {
      slug: "ondulatoria",
      name: "Ondulatória",
      frenteSlug: "frente-ondulatoria",
      frenteName: "Ondulatória e acústica",
      videoTitle:
        "ONDULATÓRIA: principais características das ondas | RESUMO DE FÍSICA PARA O ENEM",
      channel: "Curso Enem Gratuito",
      videoUrl: "https://www.youtube.com/watch?v=Rmgqv8ETn6o",
      estimatedMinutes: 20,
    },
  ],
  literatura: [
    {
      slug: "escolas-literarias",
      name: "Escolas Literárias",
      frenteSlug: "frente-escolas-literarias",
      frenteName: "Escolas literárias",
      videoTitle:
        "As 5 principais escolas literárias que caem no ENEM! - Com Professor Noslen",
      channel: "Professor Noslen",
      videoUrl: "https://www.youtube.com/watch?v=nzNytK7yVD4",
      estimatedMinutes: 20,
    },
    {
      slug: "figuras-de-linguagem-na-literatura",
      name: "Figuras de Linguagem na Literatura",
      frenteSlug: "frente-figuras-de-linguagem-literarias",
      frenteName: "Figuras de linguagem aplicadas à literatura",
      videoTitle: "Figuras de Linguagem no ENEM - Prof. Noslen",
      channel: "Professor Noslen",
      videoUrl: "https://www.youtube.com/watch?v=jOuCvHqtQBU",
      estimatedMinutes: 15,
    },
    {
      slug: "analise-de-obras",
      name: "Análise de Obras",
      frenteSlug: "frente-analise-de-obras",
      frenteName: "Análise de obras",
      videoTitle: "O Cortiço | Análise Literária [Fuvest]",
      channel: "Brasil Escola",
      videoUrl: "https://www.youtube.com/watch?v=yKyoMrfZWbg",
      estimatedMinutes: 10,
    },
    {
      slug: "teoria-literaria",
      name: "Teoria Literária",
      frenteSlug: "frente-teoria-literaria",
      frenteName: "Teoria literária",
      videoTitle: "Elementos da narrativa",
      channel: "Brasil Escola",
      videoUrl: "https://www.youtube.com/watch?v=b_KJC3YLGU8",
      estimatedMinutes: 8,
    },
  ],
  redacao: [
    {
      slug: "estrutura-dissertativo-argumentativa",
      name: "Estrutura Dissertativo-Argumentativa",
      frenteSlug: "frente-estrutura-dissertativa",
      frenteName: "Estrutura dissertativo-argumentativa",
      videoTitle: "Entenda a ESTRUTURA da REDAÇÃO do ENEM #NoENEMComNoslen",
      channel: "Professor Noslen",
      videoUrl: "https://www.youtube.com/watch?v=CjUCTZstyK8",
      estimatedMinutes: 15,
    },
    {
      slug: "repertorio-sociocultural",
      name: "Repertório Sociocultural",
      frenteSlug: "frente-repertorio-sociocultural",
      frenteName: "Repertório sociocultural",
      videoTitle: "Tipos de repertórios socioculturais para a redação",
      channel: "Brasil Escola",
      videoUrl: "https://www.youtube.com/watch?v=Inzn3de-7Ws",
      estimatedMinutes: 9,
    },
    {
      slug: "proposta-de-intervencao",
      name: "Proposta de Intervenção",
      frenteSlug: "frente-proposta-de-intervencao",
      frenteName: "Proposta de intervenção",
      videoTitle:
        "Como fazer o detalhamento na proposta de intervenção da redação do Enem?",
      channel: "Brasil Escola",
      videoUrl: "https://www.youtube.com/watch?v=FFNJ2-Y2utI",
      estimatedMinutes: 8,
      prerequisiteSummary: "Estrutura dissertativo-argumentativa",
    },
    {
      slug: "coesao-e-coerencia",
      name: "Coesão e Coerência",
      frenteSlug: "frente-coesao-e-coerencia",
      frenteName: "Coesão e coerência",
      videoTitle: "ENEM - Coesão e coerência na Redação",
      channel: "Stoodi",
      videoUrl: "https://www.youtube.com/watch?v=CCc1REeVfnw",
      estimatedMinutes: 12,
    },
  ],
  geografia: [
    {
      slug: "geografia-fisica",
      name: "Geografia Física",
      frenteSlug: "frente-geografia-fisica",
      frenteName: "Geografia física",
      videoTitle:
        "TUDO DE GEOGRAFIA FÍSICA PARA O ENEM 2026 (DIDÁTICA SUPREMA)",
      channel: "Pedro Assaad | ENEM 2026",
      videoUrl: "https://www.youtube.com/watch?v=tkn-YU7rleQ",
      estimatedMinutes: 45,
    },
    {
      slug: "geografia-da-populacao",
      name: "Geografia da População",
      frenteSlug: "frente-geografia-humana",
      frenteName: "Geografia humana e população",
      videoTitle:
        "Aula Geografia - População - Teorias Demográficas para o Enem e Vestibulares",
      channel: "Stoodi",
      videoUrl: "https://www.youtube.com/watch?v=rxLVU4iuf8k",
      estimatedMinutes: 20,
    },
    {
      slug: "geopolitica",
      name: "Geopolítica Mundial",
      frenteSlug: "frente-geopolitica",
      frenteName: "Geopolítica",
      videoTitle: "Geopolítica Mundial com o Prof. João Felipe - QG DO ENEM",
      channel: "Portal do Enem",
      videoUrl: "https://www.youtube.com/watch?v=-qMB3e-d-Ow",
      estimatedMinutes: 25,
    },
    {
      slug: "geografia-do-brasil",
      name: "Clima do Brasil",
      frenteSlug: "frente-geografia-do-brasil",
      frenteName: "Geografia do Brasil",
      videoTitle: "Clima do Brasil (Aula completa)",
      channel: "Professor Ricardo Marcílio",
      videoUrl: "https://www.youtube.com/watch?v=bEQz0HijQpA",
      estimatedMinutes: 30,
    },
  ],
  filosofia: [
    {
      slug: "filosofia-antiga",
      name: "Filosofia Antiga",
      frenteSlug: "frente-filosofia-antiga",
      frenteName: "Filosofia antiga",
      videoTitle:
        "TUDO sobre SÓCRATES, PLATÃO e ARISTÓTELES para o ENEM (FILÓSOFOS QUE MAIS CAEM)",
      channel: "Marcos Vasconcellos",
      videoUrl: "https://www.youtube.com/watch?v=b-pgy9EHvq4",
      estimatedMinutes: 25,
    },
    {
      slug: "filosofia-moderna",
      name: "Filosofia Moderna: Kant",
      frenteSlug: "frente-filosofia-moderna",
      frenteName: "Filosofia moderna",
      videoTitle: "Filosofia no Enem: Kant",
      channel: "Brasil Escola",
      videoUrl: "https://www.youtube.com/watch?v=n572kQ3xLj4",
      estimatedMinutes: 10,
      prerequisiteSummary: "Filosofia antiga (Sócrates, Platão, Aristóteles)",
    },
    {
      slug: "etica-e-politica",
      name: "Ética e Política",
      frenteSlug: "frente-etica-e-politica",
      frenteName: "Ética e política",
      videoTitle:
        "ARISTÓTELES | Ética e política - Filosofia | QUER QUE DESENHE?",
      channel: "Descomplica",
      videoUrl: "https://www.youtube.com/watch?v=0F8H9QgrYcI",
      estimatedMinutes: 12,
    },
    {
      slug: "filosofia-contemporanea",
      name: "Filosofia Contemporânea",
      frenteSlug: "frente-filosofia-contemporanea",
      frenteName: "Filosofia contemporânea",
      videoTitle: "FILOSOFIA CONTEMPORÂNEA: correntes e filósofos",
      channel: "Curso Enem Gratuito",
      videoUrl: "https://www.youtube.com/watch?v=Z9b017GY17c",
      estimatedMinutes: 20,
    },
  ],
  sociologia: [
    {
      slug: "classicos-da-sociologia",
      name: "Clássicos da Sociologia",
      frenteSlug: "frente-classicos-da-sociologia",
      frenteName: "Clássicos da sociologia",
      videoTitle: "Consolidação da Sociologia (Durkheim, Marx e Weber)",
      channel: "Vestibular X",
      videoUrl: "https://www.youtube.com/watch?v=dcg52nN1RZ8",
      estimatedMinutes: 20,
    },
    {
      slug: "cultura-e-identidade",
      name: "Cultura e Identidade",
      frenteSlug: "frente-cultura-e-identidade",
      frenteName: "Cultura e identidade",
      videoTitle: "Cultura: característica, diversidade e identidade",
      channel: "Estudo Play",
      videoUrl: "https://www.youtube.com/watch?v=dziV7pCUXDY",
      estimatedMinutes: 15,
    },
    {
      slug: "estratificacao-social",
      name: "Estratificação Social",
      frenteSlug: "frente-estratificacao-social",
      frenteName: "Estratificação social",
      videoTitle: "Estratificação social",
      channel: "Brasil Escola",
      videoUrl: "https://www.youtube.com/watch?v=DlME0zz3pW0",
      estimatedMinutes: 9,
    },
    {
      slug: "movimentos-sociais",
      name: "Movimentos Sociais",
      frenteSlug: "frente-movimentos-sociais",
      frenteName: "Movimentos sociais",
      videoTitle: "Sociologia no Enem: Novos Movimentos Sociais",
      channel: "Brasil Escola",
      videoUrl: "https://www.youtube.com/watch?v=gSk0JFYvi9o",
      estimatedMinutes: 9,
    },
  ],
  ingles: [
    {
      slug: "interpretacao-de-texto-em-ingles",
      name: "Interpretação de Texto em Inglês",
      frenteSlug: "frente-interpretacao-ingles",
      frenteName: "Interpretação de texto em inglês",
      videoTitle: "Inglês no Enem: como interpretar textos",
      channel: "English in Brazil by Carina Fragozo",
      videoUrl: "https://www.youtube.com/watch?v=jBkRAG8L12o",
      estimatedMinutes: 15,
    },
    {
      slug: "tempos-verbais",
      name: "Tempos Verbais",
      frenteSlug: "frente-tempos-verbais",
      frenteName: "Tempos verbais",
      videoTitle:
        "Aprenda TODOS os Tempos Verbais em Inglês em Menos de 30 Minutos!",
      channel: "Teacher Elza",
      videoUrl: "https://www.youtube.com/watch?v=w1TbQEPP020",
      estimatedMinutes: 28,
    },
    {
      slug: "false-cognates",
      name: "Vocabulário e False Cognates",
      frenteSlug: "frente-vocabulario-ingles",
      frenteName: "Vocabulário e falsos cognatos",
      videoTitle: "FALSE FRIENDS: Os Falsos Cognatos do Inglês",
      channel: "Teacher Elza",
      videoUrl: "https://www.youtube.com/watch?v=Tz5WW3xPzqY",
      estimatedMinutes: 15,
    },
    {
      slug: "reading-strategies",
      name: "Estratégias de Leitura para o ENEM",
      frenteSlug: "frente-reading-strategies",
      frenteName: "Estratégias de leitura",
      videoTitle: "SKIMMING E SCANNING: técnicas de leitura em inglês",
      channel: "Curso Enem Gratuito",
      videoUrl: "https://www.youtube.com/watch?v=qdkVExqTpW4",
      estimatedMinutes: 12,
    },
  ],
  espanhol: [
    {
      slug: "interpretacao-de-texto-em-espanhol",
      name: "Interpretação de Texto em Espanhol",
      frenteSlug: "frente-interpretacao-espanhol",
      frenteName: "Interpretação de texto em espanhol",
      videoTitle: "Espanhol | ENEM - Interpretação de Texto I",
      channel: "Kultivi",
      videoUrl: "https://www.youtube.com/watch?v=cidHmE1mwUY",
      estimatedMinutes: 18,
    },
    {
      slug: "heterossemanticos",
      name: "Heterossemânticos",
      frenteSlug: "frente-heterossemanticos",
      frenteName: "Heterossemânticos",
      videoTitle: "HETEROGENÉRICOS EM ESPANHOL",
      channel: "Curso Enem Gratuito",
      videoUrl: "https://www.youtube.com/watch?v=mlQ3VLolqLU",
      estimatedMinutes: 10,
    },
    {
      slug: "gramatica-basica-espanhol",
      name: "Gramática Básica: Artigos",
      frenteSlug: "frente-gramatica-espanhol",
      frenteName: "Gramática básica",
      videoTitle: "LOS ARTÍCULOS - ARTIGOS EM ESPANHOL",
      channel: "Curso Enem Gratuito",
      videoUrl: "https://www.youtube.com/watch?v=mRHjGmvrarI",
      estimatedMinutes: 10,
    },
    {
      slug: "cultura-hispano-americana",
      name: "Cultura Hispano-Americana",
      frenteSlug: "frente-cultura-hispano-americana",
      frenteName: "Cultura hispano-americana",
      videoTitle: "COMO A CULTURA HISPÂNICA CAI NO ENEM?",
      channel: "Stoodi",
      videoUrl: "https://www.youtube.com/watch?v=Qlu-YvqQKek",
      estimatedMinutes: 12,
    },
  ],
  artes: [
    {
      slug: "historia-da-arte",
      name: "História da Arte",
      frenteSlug: "frente-historia-da-arte",
      frenteName: "História da arte",
      videoTitle: "AULÃO DE ARTE PARA O ENEM: conheça os temas que mais caem",
      channel: "Curso Enem Gratuito",
      videoUrl: "https://www.youtube.com/watch?v=8jRs5CZwbQM",
      estimatedMinutes: 40,
    },
    {
      slug: "semana-de-arte-moderna",
      name: "Semana de Arte Moderna",
      frenteSlug: "frente-arte-brasileira",
      frenteName: "Arte brasileira",
      videoTitle: "SEMANA DE ARTE MODERNA (1922)",
      channel: "Curso Enem Gratuito",
      videoUrl: "https://www.youtube.com/watch?v=ubyCGWXr3h8",
      estimatedMinutes: 12,
    },
    {
      slug: "movimentos-artisticos",
      name: "Vanguardas Artísticas Europeias",
      frenteSlug: "frente-movimentos-artisticos",
      frenteName: "Movimentos artísticos",
      videoTitle: "Movimentos das vanguardas artísticas europeias",
      channel: "ProEnem - Enem 2026",
      videoUrl: "https://www.youtube.com/watch?v=Agfh3ZvjMRk",
      estimatedMinutes: 15,
    },
    {
      slug: "linguagens-artisticas",
      name: "O Que É Arte?",
      frenteSlug: "frente-linguagens-artisticas",
      frenteName: "Linguagens artísticas",
      videoTitle: "O QUE É ARTE?",
      channel: "Curso Enem Gratuito",
      videoUrl: "https://www.youtube.com/watch?v=mzRA0ClbarQ",
      estimatedMinutes: 12,
    },
  ],
  "educacao-fisica": [
    {
      slug: "cultura-corporal-e-esporte",
      name: "Cultura Corporal e Esporte",
      frenteSlug: "frente-cultura-corporal",
      frenteName: "Cultura corporal e esporte",
      videoTitle: "Educação Física | ENEM - Esportes I",
      channel: "Kultivi",
      videoUrl: "https://www.youtube.com/watch?v=ENOf3zkdDI4",
      estimatedMinutes: 18,
    },
    {
      slug: "saude-e-qualidade-de-vida",
      name: "Saúde e Qualidade de Vida",
      frenteSlug: "frente-saude-e-qualidade-de-vida",
      frenteName: "Saúde e qualidade de vida",
      videoTitle: "Educação Física | ENEM - Exercício Físico e Saúde",
      channel: "Kultivi",
      videoUrl: "https://www.youtube.com/watch?v=9MhYxGc-Ybo",
      estimatedMinutes: 18,
    },
    {
      slug: "lutas-e-ginastica",
      name: "Lutas",
      frenteSlug: "frente-lutas-e-ginastica",
      frenteName: "Lutas e ginástica",
      videoTitle: "Educação Física | ENEM - Lutas",
      channel: "Kultivi",
      videoUrl: "https://www.youtube.com/watch?v=Be4taBYyrFA",
      estimatedMinutes: 15,
    },
    {
      slug: "educacao-fisica-e-sociedade",
      name: "Educação Física e Sociedade",
      frenteSlug: "frente-educacao-fisica-e-sociedade",
      frenteName: "Educação física e mídia/sociedade",
      videoTitle:
        "TEMAS MAIS COBRADOS NO ENEM - Educação Física na prova de linguagens",
      channel: "Time A do ENEM",
      videoUrl: "https://www.youtube.com/watch?v=HwRDowZo-3k",
      estimatedMinutes: 15,
    },
  ],
};
